[tool.poetry]
name = "justdice"
version = "0.1.0"
description = ""
authors = ["sannytee <tywosanni@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
psycopg2-binary = "^2.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
